version: "3"
services:
    swarmcity_chain_parity:
        build: build
        image: swarmcity_chain_parity
        container_name: "SwarmCityChainParity"
        ports:
            - "8545:8545"
            - "8546:8546"
            - "8180:8180"
            - "8080:8080"
        volumes:
            # Parity config file
            - ./config/:/root/config/
            # Wallet Keys
            - ./data/keys:/root/keys/ethereum
            # Chain data
            - ./data/parity_chain:/root/chain
            # Parity data
            - ./data/parity_basepath:/root/.local/share/io.parity.ethereum
        command: 
             #--config /root/config/config.toml
             --db-path "/root/chain" --keys-path "/root/keys" --port 31313 --jsonrpc-port 8545 --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-cors '*' --ws-interface 0.0.0.0 --ws-port 8546 --ws-origins '*' --ws-hosts all --cache-size 1024  --no-dapps --ui-interface "0.0.0.0" --ui-hosts all --ui-no-validation --ipc-path "$HOME/.local/share/io.parity.ethereum/jsonrpc.ipc"
        restart: on-failure

